name: Retry MLflow Tracking Server Deletion (Testing Ver)

on:
  repository_dispatch:
    types: [delete-mlflow]

jobs:
  retry-delete:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MLflow deletion
        shell: bash
        run: |
          REGION="us-east-1"
          INTERVAL=60
          MAX_ATTEMPTS=$(( (120*60) / INTERVAL ))
          echo "Retrying MLflow tracking server deletion in region: $REGION"
          for ((i=1; i<=MAX_ATTEMPTS; i++)); do
            SERVERS=$(aws sagemaker list-mlflow-tracking-servers \
              --region "$REGION" \
              --query "TrackingServerSummaries[].TrackingServerName" \
              --output text 2>/dev/null || true)
            if [ -z "$SERVERS" ]; then
              echo "No MLflow tracking servers found — cleanup complete."
              exit 0
            fi
            for NAME in $SERVERS; do
              STATUS=$(aws sagemaker list-mlflow-tracking-servers \
                --region "$REGION" \
                --query "TrackingServerSummaries[?TrackingServerName=='$NAME'].TrackingServerStatus" \
                --output text 2>/dev/null || true)
              echo "Found: $NAME (status: $STATUS)"
              echo "Attempting deletion..."
              aws sagemaker delete-mlflow-tracking-server \
                --region "$REGION" \
                --tracking-server-name "$NAME" \
                && echo "Delete request sent for $NAME" \
                || echo "Delete failed or not allowed yet ($STATUS)"
            done
            sleep "$INTERVAL"
          done
          echo "Timed out after 2 hours. Some MLflow tracking servers may still exist."
          exit 1
