name: Retry MLflow Tracking Server Deletion

on:
  workflow_run:
    workflows: ["Terraform Workflow"]
    types: [completed]

jobs:
  retry-delete:
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Terraform action artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform_action
          path: ./artifact

      - name: Read Terraform action
        id: read_action
        run: |
          TERRAFORM_ACTION=$(cat ./artifact/terraform_action.txt)
          echo "Terraform action: $TERRAFORM_ACTION"
          echo "action=$TERRAFORM_ACTION" >> $GITHUB_OUTPUT

      - name: Run MLflow deletion
        if: ${{ steps.read_action.outputs.action == 'destroy' }}
        shell: bash
        run: |
          REGION="us-east-1"
          INTERVAL=60
          MAX_ATTEMPTS=$(( (120*60) / INTERVAL ))
          echo "Retrying MLflow tracking server deletion in region: $REGION"
          for ((i=1; i<=MAX_ATTEMPTS; i++)); do
            SERVERS=$(aws sagemaker list-mlflow-tracking-servers \
              --region "$REGION" \
              --query "TrackingServerSummaries[].TrackingServerName" \
              --output text 2>/dev/null || true)
            if [ -z "$SERVERS" ]; then
              echo "No MLflow tracking servers found — cleanup complete."
              exit 0
            fi
            for NAME in $SERVERS; do
              STATUS=$(aws sagemaker list-mlflow-tracking-servers \
                --region "$REGION" \
                --query "TrackingServerSummaries[?TrackingServerName=='$NAME'].TrackingServerStatus" \
                --output text 2>/dev/null || true)
              echo "Found: $NAME (status: $STATUS)"
              echo "Attempting deletion..."
              aws sagemaker delete-mlflow-tracking-server \
                --region "$REGION" \
                --tracking-server-name "$NAME" \
                && echo "Delete request sent for $NAME" \
                || echo "Delete failed or not allowed yet ($STATUS)"
            done
            sleep "$INTERVAL"
          done
          echo "Timed out after 2 hours. Some MLflow tracking servers may still exist."
          exit 1
