name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Change if needed

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      # ---------------------------------------------------------------
      # DEPLOY ACTION
      # ---------------------------------------------------------------
      - name: Terraform Fmt (Deploy only)
        if: github.event.inputs.action == 'deploy'
        run: terraform fmt -check

      - name: Terraform Plan (Deploy only)
        if: github.event.inputs.action == 'deploy'
        run: terraform plan -out=tfplan.binary

      - name: Terraform Apply (Deploy only)
        if: github.event.inputs.action == 'deploy'
        run: terraform apply -auto-approve tfplan.binary

      # ---------------------------------------------------------------
      # DESTROY ACTION
      # ---------------------------------------------------------------
      - name: Set up Python (Destroy only)
        if: github.event.inputs.action == 'destroy'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cleanup dependencies (Destroy only)
        if: github.event.inputs.action == 'destroy'
        run: |
          pip install boto3 sagemaker

      - name: Run SageMaker cleanup script (Destroy only)
        if: github.event.inputs.action == 'destroy'
        id: cleanup
        continue-on-error: true
        run: |
          echo "Running pre-destroy cleanup script..."
          if ! python -u ../clean-up-script.py; then
            echo "Cleanup failed, writing flag..."
            echo "cleanup_failed=true" >> $GITHUB_OUTPUT
          fi
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Destroy (Destroy only)
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve

